-- ============================================================================
-- Somnia Database — Partial Unique Indexes for Time-Series Tables
-- ============================================================================
-- Generated: 2026-07-11 | Schema v1.2.0
--
-- v1.2.0 NOTE: No column-name changes to partitioning columns — this file
-- is identical to v1.1.0 except for this version bump. The v1.2.0 renames
-- (pricePerRoll→pricePerPackagingUnit, fabricAreaM2→rawMaterialQuantityPerUnit,
-- etc.) affected non-partitioning columns only.
-- ============================================================================
--
-- PURPOSE
-- ───────
-- Prisma's schema DSL cannot express partial unique indexes (WHERE clauses
-- on CREATE UNIQUE INDEX). These indexes enforce "one current row per
-- logical entity" at the database level for every time-series table.
--
-- The SCD Type-2 pattern used throughout this schema defines the "current"
-- row as the one where validTo IS NULL. Without these indexes, nothing
-- prevents two rows with validTo IS NULL from existing simultaneously for
-- the same logical entity (e.g. two "current" SupplierQuote rows for the
-- same supplier + spec version).
--
-- HOW TO APPLY
-- ────────────
-- Run this file AFTER the main init migration (migration.sql). This is
-- a manual post-migration step that cannot be auto-generated by Prisma.
--
--     psql $DATABASE_URL -f partial_unique_indexes.sql
--
-- IMPORTANT NOTE ON NULL HANDLING (ManufacturingComponentCost)
-- ─────────────────────────────────────────────────────────────
-- PostgreSQL treats NULL values as distinct in unique indexes. This means
-- two rows with (componentA, NULL) do NOT violate a UNIQUE constraint on
-- (component_id, product_size_id). To handle this correctly, we create TWO
-- separate partial indexes for ManufacturingComponentCost:
--   1. For size-specific costs: UNIQUE (componentId, productSizeId) WHERE
--      productSizeId IS NOT NULL AND validTo IS NULL
--   2. For universal costs: UNIQUE (componentId) WHERE productSizeId IS NULL
--      AND validTo IS NULL
-- ============================================================================

BEGIN;

-- 1. ProductSpecVersion — one current version per product
CREATE UNIQUE INDEX product_spec_versions_one_current
    ON product_spec_versions (product_id)
    WHERE valid_to IS NULL;

-- 2. ProductSize — one current size per product+label
CREATE UNIQUE INDEX product_sizes_one_current
    ON product_sizes (product_id, size_label)
    WHERE valid_to IS NULL;

-- 3. SupplierCapability — one current assessment per supplier+spec
CREATE UNIQUE INDEX supplier_capabilities_one_current
    ON supplier_capabilities (supplier_id, product_spec_version_id)
    WHERE valid_to IS NULL;

-- 4. SupplierQuote — one current quote per supplier+spec
CREATE UNIQUE INDEX supplier_quotes_one_current
    ON supplier_quotes (supplier_id, product_spec_version_id)
    WHERE valid_to IS NULL;

-- 5. SupplierScore — one current score per supplier+spec
CREATE UNIQUE INDEX supplier_scores_one_current
    ON supplier_scores (supplier_id, product_spec_version_id)
    WHERE valid_to IS NULL;

-- 6. ShippingRoute — one current rate per route+method
CREATE UNIQUE INDEX shipping_routes_one_current
    ON shipping_routes (origin_port, destination_port, method)
    WHERE valid_to IS NULL;

-- 7. ContainerCapacity — one current capacity per spec+container type
CREATE UNIQUE INDEX container_capacities_one_current
    ON container_capacities (product_spec_version_id, container_type)
    WHERE valid_to IS NULL;

-- 8. CustomsRegime — one current regime per country+HS code
CREATE UNIQUE INDEX customs_regimes_one_current
    ON customs_regimes (country, hs_code)
    WHERE valid_to IS NULL;

-- 9. PortFee — one current fee per port+fee type
CREATE UNIQUE INDEX port_fees_one_current
    ON port_fees (port, fee_type)
    WHERE valid_to IS NULL;

-- 10. BusinessEntityStatus — one current status per entity name
CREATE UNIQUE INDEX business_entity_statuses_one_current
    ON business_entity_statuses (name)
    WHERE valid_to IS NULL;

-- 11. LaborRate — one current rate per role
CREATE UNIQUE INDEX labor_rates_one_current
    ON labor_rates (role_id)
    WHERE valid_to IS NULL;

-- 12. ManufacturingLaborTime — one current time per product size
CREATE UNIQUE INDEX manufacturing_labor_times_one_current
    ON manufacturing_labor_times (product_size_id)
    WHERE valid_to IS NULL;

-- 13. ManufacturingComponentCost — size-specific costs (productSizeId NOT NULL)
CREATE UNIQUE INDEX manufacturing_component_costs_one_current_sized
    ON manufacturing_component_costs (manufacturing_component_id, product_size_id)
    WHERE valid_to IS NULL AND product_size_id IS NOT NULL;

-- 14. ManufacturingComponentCost — universal costs (productSizeId IS NULL)
--     PostgreSQL treats NULLs as distinct in unique indexes, so a second
--     index is needed to enforce uniqueness when productSizeId is NULL.
CREATE UNIQUE INDEX manufacturing_component_costs_one_current_universal
    ON manufacturing_component_costs (manufacturing_component_id)
    WHERE valid_to IS NULL AND product_size_id IS NULL;

-- 15. ExchangeRate — one current rate per currency pair
CREATE UNIQUE INDEX exchange_rates_one_current
    ON exchange_rates (base_currency, quote_currency)
    WHERE valid_to IS NULL;

COMMIT;